### ISSUE TITLE
rake generate gives error

### ISSUE THREAD

**Issue by emilsoman** [alexharris/octopress-flat#1]
$ rake generate
## Generating Site with Jekyll
WARNING on line 35 of /home/emil/Personal/blog/sass/base/_typography.scss: "body > header h1" failed to @ extend ".heading".
  The selector ".heading" was not found.
  This will be an error in future releases of Sass.
  Use "@ extend .heading !optional" if the extend should be able to fail.

WARNING on line 77 of /home/emil/Personal/blog/sass/base/_typography.scss: "h1" failed to @ extend ".heading".
  The selector ".heading" was not found.
  This will be an error in future releases of Sass.
  Use "@ extend .heading !optional" if the extend should be able to fail.

WARNING on line 77 of /home/emil/Personal/blog/sass/base/_typography.scss: "h2" failed to @ extend ".heading".
  The selector ".heading" was not found.
  This will be an error in future releases of Sass.
  Use "@ extend .heading !optional" if the extend should be able to fail.

WARNING on line 77 of /home/emil/Personal/blog/sass/base/_typography.scss: "h3" failed to @ extend ".heading".
  The selector ".heading" was not found.
  This will be an error in future releases of Sass.
  Use "@ extend .heading !optional" if the extend should be able to fail.

WARNING on line 77 of /home/emil/Personal/blog/sass/base/_typography.scss: "h4" failed to @ extend ".heading".
  The selector ".heading" was not found.
  This will be an error in future releases of Sass.
  Use "@ extend .heading !optional" if the extend should be able to fail.

WARNING on line 77 of /home/emil/Personal/blog/sass/base/_typography.scss: "h5" failed to @ extend ".heading".
  The selector ".heading" was not found.
  This will be an error in future releases of Sass.
  Use "@ extend .heading !optional" if the extend should be able to fail.

WARNING on line 77 of /home/emil/Personal/blog/sass/base/_typography.scss: "h6" failed to @ extend ".heading".
  The selector ".heading" was not found.
  This will be an error in future releases of Sass.
  Use "@ extend .heading !optional" if the extend should be able to fail.

WARNING on line 16 of /home/emil/Personal/blog/sass/partials/sidebar/_base.scss: "aside.sidebar section h1" failed to @ extend ".side-shadow-border".
  The selector ".side-shadow-border" was not found.
  This will be an error in future releases of Sass.
  Use "@ extend .side-shadow-border !optional" if the extend should be able to fail.

**Comment by alexharris** [comment]
Hi, I am not experiencing this issue. It looks like the errors are occurring in /home/emil/Personal/blog/sass/. Is that where you moved this theme to? Did you already run rake install?

**Comment by emilsoman** [comment]
I cloned the theme to [blog-source-branch-root]/.themes/octopress-flat. I ran `rake install['octopress-flat']` . The errors are seen when I run `rake generate` after these steps. Where are these classes `heading`  and `side-shadow-border` defined ?

**Comment by alexharris** [comment]
They were in various scss files. See this commit: a3675c98f1dfd63b5a0498599e0315bf164a4a7d

I removed them. Trying pulling, installing, and generating again.

**Comment by emilsoman** [comment]
I'll take a pull and update the status. Thanks !

**Comment by alexharris** [comment]
Cool, let me know how it goes

**Comment by emilsoman** [comment]
Errors are gone now. Thanks ! But I'm facing another problem and I don't know if it's related to this issue so I don't want to open another one. I'm not able to get the theme working on my octopress blog. [You can see the blog's source on GitHub](https://github.com/emilsoman/emilsoman.github.com) . These are the steps I followed : 

```
$ cd blog
$ git clone git://github.com/alexharris/octopress-flat.git .themes/octopress-flat
$ rake install['octopress-flat']
$ rake preview
```

There are no errors. Cleared the browser cache and refreshed my preview page and I'm not seeing the flat UI. Is there anything else I need to do ?

**Comment by alexharris** [comment]
Does that workflow work on other themes? I just tried what you said, and it seemed to work, although there seems to be some weirdness around "rake preview". According to the octopress documentation:

rake generate   # Generates posts and pages into the public directory
rake watch      # Watches source/ and sass/ for changes and regenerates
rake preview    # Watches, and mounts a webserver at http://localhost:4000

So maybe rake preview is not the right option. Try doing rake install and then rake generate. For me, this consistently works.

**Comment by alexharris** [comment]
Hey, did this end up working? If so, I'd like to close the issue. Thanks.

**Comment by emilsoman** [comment]
@alexharris , sorry for the delay . Yeah `rake preivew` gives a messed up UI. `rake generate` works though ( But it's weird that `rake preview` works on other themes that I've tried ) . This issue can be closed . Thanks !

**Comment by alexharris** [comment]
Thanks. I'd look into it, but with Octopress 3 on the horizon, I'm reluctant to put much further work into this version.
