### ISSUE TITLE
{% codeblock %} tags seem to have broken styling

### ISSUE THREAD

**Issue by davidcelis** [alexharris/octopress-flat#2]
Hey; I love the theme so far but, when I install it onto my blog, codeblock tags seem to lose their styles. The line-number gutters and code have no discernable difference, except that the line-heights are all off so none of the line numbers align correctly with the code.

Also, the code blocks no longer get syntax highlighting for some reason.

I noticed on your personal site, you fixed, at the least, styling for the gutter and line-height.

**Comment by davidcelis** [comment]
Wow, this is totally the wrong octopress flat theme. Sorry.

**Comment by alexharris** [comment]
Hey, no problem. The other octopress flat theme guy and I should probably work something out, name-wise.
