### ISSUE TITLE
Sidebar search inconsistent?

### ISSUE THREAD

**Issue by seanfisk** [alexharris/octopress-flat#7]
Hi Alex,

First of all I would like to say thanks for your theme! It is simple yet attractive, and we are currently using it for our site http://gvtools.org/.

We wanted to have the search box display on every page of the site, but we found that it only displayed on the home page (`source/index.html`). We fixed it by creating a sidebar include that gets included in these files:
- `source/_layouts/page.html`
- `source/_layouts/post.html`
- `source/index.html`

I'd be happy to make a pull request to "fix" this, but was the search box intended to only be displayed on the home page?

Thanks!

**Comment by alexharris** [comment]
Hi Sean,

Glad you like the theme. Your implementation of it is looking great.

I think it makes sense to display the search box on all pages, not just the homepage. Please feel free to submit a pull request.

thanks,

Alex

P.S. It's not a big deal I am sure, but I always like to point out that Octopress 3.0 is coming out sometime soon, and I am just not sure what support there will be from the creator, if any, for 2.0.

**Comment by seanfisk** [comment]
> Your implementation of it is looking great.

Thanks!

> Please feel free to submit a pull request.

Will do. We also noticed that the nav bar, which is not visible by default in this theme, contains a search box too. Just so future users don't get confused, it might be beneficial to remove it from there. I'll include it in the pull request and you can comment or cherry-pick if you don't like it.

> Octopress 3.0 is coming out sometime soon, and I am just not sure what support there will be from the creator, if any, for 2.0.

That's awesome! I'm glad to hear that, since there hasn't been a major release in a while. We'll keep working with 2.0 for now, but when it comes out we may consider migrating. We don't have much content/style mods at this point anyway.

**Comment by alexharris** [comment]
Oh yeah, I'm happy to be rid of the extra search box. It would seem that I just got the theme working for myself, and didn't bother with any other use cases. oops :)

Yeah, I think 3.0 is gonna be pretty different, like maybe just a ruby gem or something to include in jekyll/rails projects. Last I checked it didn't look like 2.0 themes would be forward compatible, although I didn't look into it too thoroughly. Just something to think about before sinking too much time into 2.0 theming.

**Comment by seanfisk** [comment]
OK, thanks for the tips. A Ruby Gem would make the impl. a little cleaner. PR soon :)

> It would seem that I just got the theme working for myself, and didn't bother with any other use cases. oops :)

No apology necessary. That's why free/open-source software is awesome!

**Comment by alexharris** [comment]
Thanks for the commit Sean. Please let me know if anything else comes up. And I will have check back in later and see how the site turns out when its in full swing.

**Comment by seanfisk** [comment]
Will do. Thanks for the theme and being responsive!
